//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationOutage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outage
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Impact { get; set; }
        public string Description { get; set; }
        public string Component { get; set; }
        public string IncidentNumber { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
